{
 "title": "LexRAG Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Questions Answered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Total_Question_Answered\r\nFROM evaluation_data \r\n--GROUP BY 1"
    }
   ]
  },
  {
   "title": "Users Filled Feedback",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) Users_Filled_Feedback\r\nFROM feedback_data "
    }
   ]
  },
  {
   "title": "Users Satisfaction Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\r\n  COUNT(CASE WHEN is_satisfied = TRUE THEN id ELSE NULL END)/COUNT(id)::float AS Users_Satisfaction\r\nFROM feedback_data "
    }
   ]
  },
  {
   "title": "LLM Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_time,\r\n  response_time\r\nFROM evaluation_data "
    }
   ]
  },
  {
   "title": "LLM's Score Performance ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_time,\r\n  llm_score,\r\n  mrr_score,\r\n  hit_rate_score\r\nFROM evaluation_data "
    }
   ]
  }
 ]
}